name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:pass@localhost:5432/simple_service_test?sslmode=disable
      JWT_SECRET: "super_test_secret"
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: simple_service_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      
      - name: Install golang-migrate CLI
        run: |
          go install -tags "postgres" github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      - name: Add Go bin to PATH
        run: echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Wait for DB
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for postgres…"
            sleep 1
          done

      - name: Run tests
        env:
          DATABASE_URL: "postgres://postgres:pass@localhost:5432/simple_service_test?sslmode=disable"
        run: go test ./... -v
